# Global Values for 2bshops application - Local Development Configuration
global:
  environment: local
  domain: localhost

frontend:
  replicaCount: 1
  image:
    repository: localhost:5000/frontend
    tag: latest
    pullPolicy: Always
    service:
    type: NodePort
    port: 80
      # Environment variables via ConfigMap for local development
  configMap:
    VITE_API_URL: "http://localhost:8000"
    NODE_ENV: "development"

backend:
  replicaCount: 1
  image:
    repository: localhost:5000/backend
    tag: latest
    pullPolicy: Always
    service:
    type: NodePort
    port: 8000
      # Non-sensitive environment variables via ConfigMap for local development
  configMap:
    DOMAIN: "localhost"
    ENVIRONMENT: "local" 
    BACKEND_CORS_ORIGINS: "http://localhost,http://localhost:3000,http://localhost:5173,http://localhost:80,http://localhost"
    PROJECT_NAME: "2B Shops Dev"
  # Sensitive data stored in Kubernetes Secrets
  # For local development, using simpler default values
  secrets:
    SECRET_KEY: "local-dev-secret-key-change-in-production"
    FIRST_SUPERUSER: "admin@example.com"
    FIRST_SUPERUSER_PASSWORD: "localdevpassword"
  # Database configuration
  database:
    host: "app2bshops-postgresql"
    port: 5432
    name: "app"
    user: "postgres"
    password: "localdevdbpassword"

# PostgreSQL configuration
postgresql:
  enabled: true
  image:
    tag: "12"
  auth:
    postgresPassword: "localdevdbpassword"
    username: postgres
    password: "localdevdbpassword" 
    database: app
  primary:
    persistence:
      enabled: true
      size: 1Gi  # Smaller size for local development
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
