apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-db-secrets
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.database.user }}
  POSTGRES_USER: {{ .Values.database.user | b64enc | quote }}
  {{- end }}
  {{- if .Values.database.password }}
  POSTGRES_PASSWORD: {{ .Values.database.password | b64enc | quote }}
  {{- end }}
