apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secrets
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.SECRET_KEY }}
  SECRET_KEY: {{ .Values.secrets.SECRET_KEY | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.FIRST_SUPERUSER }}
  FIRST_SUPERUSER: {{ .Values.secrets.FIRST_SUPERUSER | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.FIRST_SUPERUSER_PASSWORD }}
  FIRST_SUPERUSER_PASSWORD: {{ .Values.secrets.FIRST_SUPERUSER_PASSWORD | b64enc | quote }}
  {{- end }}
