{{- if .Values.secretProvider.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: {{ .Values.secretProvider.keyVaultName | quote }}
    cloudName: ""
    objects: |
      array:
        - |
          objectName: SECRET-KEY
          objectType: secret
          objectVersion: ""
        - |
          objectName: POSTGRES-PASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: FIRST-SUPERUSER
          objectType: secret
          objectVersion: ""
        - |
          objectName: FIRST-SUPERUSER-PASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: SMTP-HOST
          objectType: secret
          objectVersion: ""
        - |
          objectName: SMTP-USER
          objectType: secret
          objectVersion: ""
        - |
          objectName: SMTP-PASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: SENTRY-DSN
          objectType: secret
          objectVersion: ""
    tenantId: {{ .Values.secretProvider.tenantId | quote }}
  secretObjects:
    - data:
      - key: SECRET_KEY
        objectName: SECRET-KEY
      - key: FIRST_SUPERUSER
        objectName: FIRST-SUPERUSER
      - key: FIRST_SUPERUSER_PASSWORD
        objectName: FIRST-SUPERUSER-PASSWORD
      - key: SMTP_HOST
        objectName: SMTP-HOST
      - key: SMTP_USER
        objectName: SMTP-USER
      - key: SMTP_PASSWORD
        objectName: SMTP-PASSWORD
      - key: SENTRY_DSN
        objectName: SENTRY-DSN
      secretName: {{ .Release.Name }}-secrets
      type: Opaque
    - data:
      - key: POSTGRES_PASSWORD
        objectName: POSTGRES-PASSWORD
      - key: POSTGRES_USER
        objectName: postgres
      secretName: {{ .Release.Name }}-db-secrets
      type: Opaque
{{- end -}}
