"""Add compliance table

Revision ID: 1c104ca518ce
Revises: b0ac4a72eeb3
Create Date: 2025-03-28 08:58:27.941785

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1c104ca518ce'
down_revision = 'b0ac4a72eeb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
