"""Add stored procedure get_compliances_by_name

Revision ID: 53ecbfa4fd58
Revises: eb3d986a5e9c
Create Date: 2025-03-28 12:27:42.310446

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '53ecbfa4fd58'
down_revision = 'eb3d986a5e9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_compliance_id', table_name='compliance')
    op.drop_index('ix_compliance_name', table_name='compliance')
    op.create_index(op.f('ix_compliance_name'), 'compliance', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compliance_name'), table_name='compliance')
    op.create_index('ix_compliance_name', 'compliance', ['name'], unique=False)
    op.create_index('ix_compliance_id', 'compliance', ['id'], unique=False)
    # ### end Alembic commands ###
