"""Add compliance table

Revision ID: b0ac4a72eeb3
Revises: ef62c4cd00e4
Create Date: 2025-03-28 08:42:24.383996

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b0ac4a72eeb3'
down_revision = 'ef62c4cd00e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_id'), 'compliance', ['id'], unique=False)
    op.create_index(op.f('ix_compliance_name'), 'compliance', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compliance_name'), table_name='compliance')
    op.drop_index(op.f('ix_compliance_id'), table_name='compliance')
    op.drop_table('compliance')
    # ### end Alembic commands ###
