"""Add Compliance model

Revision ID: eb3d986a5e9c
Revises: 1c104ca518ce
Create Date: 2025-03-28 10:32:10.880861

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'eb3d986a5e9c'
down_revision = '1c104ca518ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
