name: Push to ACR
description: Push Docker images and Helm charts to Azure Container Registry (ACR)

concurrency: production

on:
  push:
    # paths:
    #   - 'frontend/**'
    #   - 'backend/**'
    #   - 'charts/**'
    branches:
     - master

  release:
    types:
      - published

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set SHORT_SHA & VERSION
        run: |
          echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.1.0")
          # Remove leading 'v' if present
          echo "VERSION=${LATEST_TAG#v}" >> $GITHUB_ENV

      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
      # Login to ACR
      - name: Login to ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{ vars.ACR_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Build and push Docker images
      - name: Build and push frontent docker image
        uses: ./.github/actions/build-push-docker
        with:
          app-name: frontend
          app-tag: ${{ env.SHORT_SHA }}
          acr-server: ${{ vars.ACR_SERVER }}
          stack-name: ${{ vars.STACK_NAME_PRODUCTION }}
      - name: Build and push backend docker image
        uses: ./.github/actions/build-push-docker
        with:
          app-name: backend
          app-tag: ${{ env.SHORT_SHA }}
          acr-server: ${{ vars.ACR_SERVER }}
          stack-name: ${{ vars.STACK_NAME_PRODUCTION }}

        # Package and push helm charts
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'
      - name: Login to ACR
        run: helm registry login ${{  vars.ACR_SERVER }} -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
      - name: Update Helm dependencies
        run: |
          cd charts/app2bshops
          helm dependency update
      - name: Push frontend helm charts
        uses: ./.github/actions/push-helm
        with:
          chart-name: frontend
          sha-tag: ${{ env.SHORT_SHA }}
          app-version: ${{ env.VERSION }}
          acr-name: ${{ vars.ACR_SERVER }}
      - name: Push backend helm charts
        uses: ./.github/actions/push-helm
        with:
          chart-name: backend
          sha-tag: ${{ env.SHORT_SHA }}
          app-version: ${{ env.VERSION }}
          acr-name: ${{ vars.ACR_SERVER }}
      - name: Push umbrella helm charts
        uses: ./.github/actions/push-helm
        with:
          chart-name: app2bshops
          sha-tag: ${{ env.SHORT_SHA }}
          app-version: ${{ env.VERSION }}
          acr-name: ${{ vars.ACR_SERVER }}
