apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: app-db-data-pvc
  name: app-db-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
