apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - image: {{ .Values.image.frontend }}
          name: frontend
          env:
            - name: VITE_API_URL
              value: {{ .Values.environment.VITE_API_URL }}
            - name: NODE_ENV
              value: {{ .Values.environment.NODE_ENV }}
          ports:
            - containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 3
            periodSeconds: 5
            timeoutSeconds: 3
      restartPolicy: Always
